config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :departments
  resources :positions
	root 'users#index'
	resources :users
	post 'users/fire' => 'users#fire'
	get 'transactions/:user_id' => 'transactions#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
	validates :name, :presence => { :message => "Нужно задать имя должности" }

	@@cahed_positions = nil


	def self.get_name_by_id id
		cahed_positions[id]
	end

	def self.reset_cahed_positions
		@@cahed_positions = nil	
	end

	def self.cahed_positions
    	return @@cahed_positions if @@cahed_positions.present?
    	@@cahed_positions = Position.all.inject({}){|res, p| res[p.id] = p.name; res}
  	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    Position.reset_cahed_positions
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Должность успешно создана.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    Position.reset_cahed_positions
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Название дожности изменено.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper

	def self.prepare_for_select_box 
		ApplicationHelper.prepare_for_select_box Position.cahed_positions	
	end

end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибка:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Должность" %>
    <%= form.text_field :name, id: :position_name %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<%= render 'form', position: @position %>

<%= link_to 'К списку должностей', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Должности</h1>

<%= link_to '+  Добавить должность', new_position_path %>


<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td><%= link_to 'Изменить', edit_position_path(position) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/positions/new.html.erb
<h1>Новая должность</h1>

<%= render 'form', position: @position %>

<%= link_to 'К списку должностей', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Должность:</strong>
  <%= @position.name %>
</p>

<%= link_to 'Редактировать', edit_position_path(@position) %> |
<%= link_to 'К списку должностей', positions_path %>