config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :departments
  resources :positions
	root 'users#index'
	resources :users
	post 'users/fire' => 'users#fire'
	get 'transactions/:user_id' => 'transactions#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	
	validates :first_name, :presence => { :message => "Нужно задать имя" }
	validates :last_name, :presence => { :message => "Нужно задать фамилию" }

	belongs_to :department
  	validates :department_id, :presence => { :message => "Нужно задать отдел" }

  	belongs_to :position
  	validates :position_id, :presence => { :message => "Нужно задать должность" }

  	validates :state, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 1,  :message => "Неверно задан статус" }

  	validates :salary, :numericality => { :greater_than => 0,  :message => "Неверно задан размер оклада" }

	attr_accessor :is_new

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  USER_PARAMS_FOR_TRACK = {
    "department_id" => TransactionsHelper::DEPARTMENT_TYPE, 
    "position_id" => TransactionsHelper::POSITION_TYPE, 
    "salary" => TransactionsHelper::SALARY_TYPE
  }

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.state = UsersHelper::WORK_STATE
    @user.is_new = true
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.state = UsersHelper::WORK_STATE
    
    respond_to do |format|
      if @user.save
        Transaction.add_transaction(@user.id, TransactionsHelper::ACCEPT_JOB_TYPE)
        format.html { redirect_to @user, notice: 'Сотрудник успешно создан.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def fire
    @user = User.find(params["user_id"].to_i)
    respond_to do |format|
      if @user.present?
        @user.state = UsersHelper::FIRED_STATE
        @user.save
        Transaction.add_transaction(@user.id, TransactionsHelper::FIRE_JOB_TYPE, nil, params['reason'])
        format.html { redirect_to users_path, notice: 'Сотрудник уволен.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    old_user = User.find(params["id"])

    USER_PARAMS_FOR_TRACK.each{|param_name, transaction_type_id| 
      old_val = old_user[param_name].to_s
      new_val = user_params[param_name].to_s
      Transaction.add_transaction(
        params["id"], 
        transaction_type_id, 
        nil, 
        Transaction.user_val_description(transaction_type_id, new_val), 
        Transaction.user_val_description(transaction_type_id, old_val)
      ) if new_val != old_val
    }
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Изменения сохранены.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Сотрудник удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :department_id, :position_id, :salary, :state)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	WORK_STATE = 1
	FIRED_STATE = 0
	STATES = {FIRED_STATE => "Уволен", WORK_STATE => "Работает"}
end

app/views/users/_form.html.erb
<% if user.state.to_i != UsersHelper::FIRED_STATE %>
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2>Ошибка:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label "Фамилия" %>
      <%= form.text_field :last_name, id: :user_last_name %>
    </div>

    <div class="field">
      <%= form.label "Имя" %>
      <%= form.text_field :first_name, id: :user_first_name %>
    </div>

    <div class="field">
      <%= form.label "Отдел" %>
      <%= form.select(:department_id, options_for_select(DepartmentsHelper.prepare_for_select_box, user.department_id.to_i)) %>
    </div>

    <div class="field">
      <%= form.label "Должность" %>
      <%= form.select(:position_id, options_for_select(PositionsHelper.prepare_for_select_box, user.position_id.to_i)) %>
    </div>

    <div class="field">
      <%= form.label "Оклад" %>
      <%= form.number_field :salary, id: :user_salary %>
    </div>

    <% if !user.is_new %>
      <div class="field">
        <%= form.label "Статус" %>
        <%= UsersHelper::STATES[user.state.to_i] %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit "Сохранить" %>
    </div>
  <% end %>

  <br>
  <br>

  <% if !user.is_new %>
    <%= form_tag("/users/fire", method: "post") do %>
      <%= hidden_field_tag "user_id", user.id %>
      <%= label_tag(:reason, "Причина увольнения") %>
      <%= text_field_tag(:reason) %>
      <%= submit_tag("Уволить") %>
    <% end %>
  <% end %>

<% end %>

<% if !user.is_new %>
    <%= link_to 'Посмотреть историю изменений', controller: 'transactions', :action => "show" %>
<% end %>




<br>
<br>

app/views/users/edit.html.erb
<h1>Данные сотрудника</h1>

<%= render 'form', user: @user %>

<%= link_to 'К списку сотрудников', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Сотрудники</h1>

<%= link_to '+ Добавить сотрудника', new_user_path %>

<table>
  <thead>
    <tr>
      <th>№</th>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отдел</th>
      <th>Должность</th>
      <th>Зарплата</th>
      <th>Статус</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= Department.get_name_by_id(user.department_id) %></td>
        <td><%= Position.get_name_by_id(user.position_id) %></td>
        <td><%= user.salary %></td>
        <td><%= UsersHelper::STATES[user.state] %></td>
        <td><%= link_to 'Редактировать', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Новый сотрудник</h1>

<%= render 'form', user: @user %>

<%= link_to 'К списку сотрудников', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Фамилия:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Отдел:</strong>
  <%= Department.get_name_by_id(@user.department_id) %>
</p>

<p>
  <strong>Должность:</strong>
  <%= Position.get_name_by_id(@user.position_id) %>
</p>

<p>
  <strong>Оклад:</strong>
  <%= @user.salary %>
</p>

<p>
  <strong>Статус:</strong>
  <%= UsersHelper::STATES[@user.state] %>
</p>

<%= link_to 'Изменить', edit_user_path(@user) %> |
<%= link_to 'К списку сотрудников', users_path %>