config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :departments
  resources :positions
	root 'users#index'
	resources :users
	post 'users/fire' => 'users#fire'
	get 'transactions/:user_id' => 'transactions#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
	validates :name, :presence => { :message => "Нужно задать имя отдела" }

	@@cahed_departments = nil

	def self.get_name_by_id id
		cahed_departments[id]
	end

	def self.reset_cahed_departments
		@@cahed_departments = nil	
	end

	def self.cahed_departments
    	return @@cahed_departments if @@cahed_departments.present?
    	@@cahed_departments = Department.all.inject({}){|res, p| res[p.id] = p.name; res}
  	end


end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    Department.reset_cahed_departments
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Отдел был успешно создан.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    Department.reset_cahed_departments
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Отдел был успешно изменен.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper

	def self.prepare_for_select_box 
		ApplicationHelper.prepare_for_select_box Department.cahed_departments	
	end

end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибка:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Отдел" %>
    <%= form.text_field :name, id: :department_name %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<%= render 'form', department: @department %>

<%= link_to 'К списку отделов', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Отделы</h1>

<%= link_to '+  Добавить отдел', new_department_path %>


<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= link_to 'Изменить', edit_department_path(department) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/departments/new.html.erb
<h1>Новый отдел</h1>

<%= render 'form', department: @department %>

<%= link_to 'К списку отделов', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Отдел:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Редактировать', edit_department_path(@department) %> |
<%= link_to 'К списку отделов', departments_path %>